{
 "title": "POD 监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(container_cpu_usage_seconds_total,pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "应用堆内存",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "repeat": "memarea",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",pod=~\"$pod\"} / jvm_memory_bytes_max{pod=~\"$pod\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "POD Memory 使用百分比",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{container_name!=\"POD\",container_name!=\"\",pod_name=~\"$pod\"} - container_memory_cache{container_name!=\"POD\",container_name!=\"\",pod_name=~\"$pod\"})/container_spec_memory_limit_bytes{container_name!=\"POD\",container_name!=\"\",pod_name=~\"$pod\"}",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "POD CPU 使用百分比",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum by (pod)(rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\",container_name!=\"POD\",pod_name=~\"$pod\"}[1m])))/(sum by (pod)(kube_pod_container_resource_limits_cpu_cores{pod=~\"$pod\"}))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "POD 应用GC情况",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{pod=~\"$pod\"}[$__interval])",
     "legendFormat": "{{ pod }}--{{gc}}"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    },
    {}
   ]
  },
  {
   "title": "JVM deadlocked threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_deadlocked{pod=~\"$pod\"}"
    },
    {}
   ]
  },
  {
   "title": "POD Network I/O 入口流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{job=\"kubelet\",pod_name!=\"\",pod_name=~\"$pod\"}[1m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "POD Network I/O出口流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_transmit_bytes_total{job=\"kubelet\",pod_name!=\"\",pod_name=~\"$pod\"}[1m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  }
 ]
}